[package]
name = "calc"
version = "0.1.0"
edition = "2024"

[dependencies]
num-rational = { version = "0.4.2" }
binary-tree = "0.2.0"

[[bin]]
path = "src/bin/main.rs"
name = "main"

[lib]
path = "src/lib/lib.rs"