[package]
name = "calc"
version = "0.1.0"
edition = "2024"

[dependencies]
num-rational = { version = "0.4.2" }
syntree = { version = "0.18.0" }

[[bin]]
path = "src/bin/main.rs"
name = "main"

[lib]
path = "src/lib/lib.rs"